---
- name: Download Composer
  get_url: url=https://getcomposer.org/installer dest=/tmp/composer_installer mode=0755

- name: Install Composer
  shell:
    php /tmp/composer_installer -- --filename=composer --install-dir=/usr/local/bin
    creates='/usr/local/bin/composer'
    chdir='/tmp'
  become: yes
  become_method: sudo
